# Netlify build configuration file

[build]
  # This tells Netlify where your functions folder is located.
  functions = "netlify/functions"

# This is a rule to make sure your single-page app works correctly.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


  # FILE: netlify.toml

[functions]
  included_files = ["./service-account.json"] # If you have a file

# === CHANGED: Schedule a "0 * * * *" kore din ===
# Schedule the function to run once every hour
[functions."auto-approve-submissions"]
  schedule = "0 * * * *"